import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Teste de Nivelamento</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cropped-4-2.png" />
      </Head>


      <footer className={styles.footer}>
        <a
          href="https://github.com/afgmlff"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/me.jpg" width={16} height={16} className={styles.roundedImg} alt={''} />
          </span>
        </a>
      </footer>
    </div>
  )
}
