import React from "react"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';

import Home from './index'

function Resultado(){
    return (
        <div className={styles.container}>
            <Head>
                <title>Teste de Nivelamento - Resultados</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/cropped-4-2.png" />
            </Head>

            <main>
                <div className={styles.centralizeCont}>
                    <h1>Resultados: </h1>
                </div>
            </main>
        </div>
    )
    
    }
    
    export default Resultado
